/**
 * International country dial codes.
 * Format: { code: '+91', country: 'India', flag: '🇮🇳' }
 * Sorted: popular countries first, then alphabetically.
 */
export const COUNTRY_CODES = [
  { code: '+1',   country: 'United States', flag: '🇺🇸' },
  { code: '+91',  country: 'India',         flag: '🇮🇳' },
  { code: '+44',  country: 'United Kingdom',flag: '🇬🇧' },
  { code: '+61',  country: 'Australia',     flag: '🇦🇺' },
  { code: '+81',  country: 'Japan',         flag: '🇯🇵' },
  { code: '+49',  country: 'Germany',       flag: '🇩🇪' },
  { code: '+33',  country: 'France',        flag: '🇫🇷' },
  { code: '+86',  country: 'China',         flag: '🇨🇳' },
  { code: '+55',  country: 'Brazil',        flag: '🇧🇷' },
  { code: '+7',   country: 'Russia',        flag: '🇷🇺' },
  { code: '+82',  country: 'South Korea',   flag: '🇰🇷' },
  { code: '+34',  country: 'Spain',         flag: '🇪🇸' },
  { code: '+39',  country: 'Italy',         flag: '🇮🇹' },
  { code: '+31',  country: 'Netherlands',   flag: '🇳🇱' },
  { code: '+46',  country: 'Sweden',        flag: '🇸🇪' },
  { code: '+47',  country: 'Norway',        flag: '🇳🇴' },
  { code: '+45',  country: 'Denmark',       flag: '🇩🇰' },
  { code: '+41',  country: 'Switzerland',   flag: '🇨🇭' },
  { code: '+43',  country: 'Austria',       flag: '🇦🇹' },
  { code: '+32',  country: 'Belgium',       flag: '🇧🇪' },
  { code: '+351', country: 'Portugal',      flag: '🇵🇹' },
  { code: '+30',  country: 'Greece',        flag: '🇬🇷' },
  { code: '+48',  country: 'Poland',        flag: '🇵🇱' },
  { code: '+90',  country: 'Turkey',        flag: '🇹🇷' },
  { code: '+20',  country: 'Egypt',         flag: '🇪🇬' },
  { code: '+27',  country: 'South Africa',  flag: '🇿🇦' },
  { code: '+234', country: 'Nigeria',       flag: '🇳🇬' },
  { code: '+254', country: 'Kenya',         flag: '🇰🇪' },
  { code: '+233', country: 'Ghana',         flag: '🇬🇭' },
  { code: '+212', country: 'Morocco',       flag: '🇲🇦' },
  { code: '+213', country: 'Algeria',       flag: '🇩🇿' },
  { code: '+216', country: 'Tunisia',       flag: '🇹🇳' },
  { code: '+971', country: 'UAE',           flag: '🇦🇪' },
  { code: '+966', country: 'Saudi Arabia',  flag: '🇸🇦' },
  { code: '+965', country: 'Kuwait',        flag: '🇰🇼' },
  { code: '+974', country: 'Qatar',         flag: '🇶🇦' },
  { code: '+973', country: 'Bahrain',       flag: '🇧🇭' },
  { code: '+968', country: 'Oman',          flag: '🇴🇲' },
  { code: '+962', country: 'Jordan',        flag: '🇯🇴' },
  { code: '+961', country: 'Lebanon',       flag: '🇱🇧' },
  { code: '+972', country: 'Israel',        flag: '🇮🇱' },
  { code: '+92',  country: 'Pakistan',      flag: '🇵🇰' },
  { code: '+880', country: 'Bangladesh',    flag: '🇧🇩' },
  { code: '+94',  country: 'Sri Lanka',     flag: '🇱🇰' },
  { code: '+977', country: 'Nepal',         flag: '🇳🇵' },
  { code: '+95',  country: 'Myanmar',       flag: '🇲🇲' },
  { code: '+66',  country: 'Thailand',      flag: '🇹🇭' },
  { code: '+84',  country: 'Vietnam',       flag: '🇻🇳' },
  { code: '+60',  country: 'Malaysia',      flag: '🇲🇾' },
  { code: '+65',  country: 'Singapore',     flag: '🇸🇬' },
  { code: '+62',  country: 'Indonesia',     flag: '🇮🇩' },
  { code: '+63',  country: 'Philippines',   flag: '🇵🇭' },
  { code: '+64',  country: 'New Zealand',   flag: '🇳🇿' },
  { code: '+52',  country: 'Mexico',        flag: '🇲🇽' },
  { code: '+54',  country: 'Argentina',     flag: '🇦🇷' },
  { code: '+56',  country: 'Chile',         flag: '🇨🇱' },
  { code: '+57',  country: 'Colombia',      flag: '🇨🇴' },
  { code: '+51',  country: 'Peru',          flag: '🇵🇪' },
  { code: '+58',  country: 'Venezuela',     flag: '🇻🇪' },
  { code: '+593', country: 'Ecuador',       flag: '🇪🇨' },
  { code: '+502', country: 'Guatemala',     flag: '🇬🇹' },
  { code: '+1876',country: 'Jamaica',       flag: '🇯🇲' },
  { code: '+1868',country: 'Trinidad & Tobago', flag: '🇹🇹' },
  { code: '+40',  country: 'Romania',       flag: '🇷🇴' },
  { code: '+36',  country: 'Hungary',       flag: '🇭🇺' },
  { code: '+420', country: 'Czech Republic',flag: '🇨🇿' },
  { code: '+421', country: 'Slovakia',      flag: '🇸🇰' },
  { code: '+380', country: 'Ukraine',       flag: '🇺🇦' },
  { code: '+375', country: 'Belarus',       flag: '🇧🇾' },
  { code: '+358', country: 'Finland',       flag: '🇫🇮' },
  { code: '+353', country: 'Ireland',       flag: '🇮🇪' },
  { code: '+354', country: 'Iceland',       flag: '🇮🇸' },
  { code: '+385', country: 'Croatia',       flag: '🇭🇷' },
  { code: '+386', country: 'Slovenia',      flag: '🇸🇮' },
  { code: '+387', country: 'Bosnia',        flag: '🇧🇦' },
  { code: '+381', country: 'Serbia',        flag: '🇷🇸' },
  { code: '+389', country: 'North Macedonia', flag: '🇲🇰' },
  { code: '+355', country: 'Albania',       flag: '🇦🇱' },
  { code: '+995', country: 'Georgia',       flag: '🇬🇪' },
  { code: '+374', country: 'Armenia',       flag: '🇦🇲' },
  { code: '+994', country: 'Azerbaijan',    flag: '🇦🇿' },
  { code: '+7',   country: 'Kazakhstan',    flag: '🇰🇿' },
  { code: '+998', country: 'Uzbekistan',    flag: '🇺🇿' },
]

/** Returns options formatted for the existing Select component. */
export const COUNTRY_CODE_OPTIONS = COUNTRY_CODES.map(c => ({
  value: c.code,
  label: `${c.flag} ${c.code} ${c.country}`,
}))
